### ISSUE TITLE
Error while running npm start.

### ISSUE THREAD

**Issue by CSharpDriver** [dodekeract/apm#1]
Hi
I got error messages when trying to do npm start on a project.  The log is attached.  

[npm-debug.log](https://github.com/dodekeract/apm/files/1349236/npm-debug.log)

Any help on fixing this would be greatly appreciated.

Thanks
Merv Rutt
mervrutt@yahoo.com

**Comment by FlorianWendelborn** [comment]
You're using version `0.0.0`. The project changed ownership with `1.0.0.` and no longer uses the original (non-existent codebase). Are you sure that you intended it to be used inside your project?

If you don't know why `apm` is inside your project, use `npm remove --save apm` and try again.

**Comment by CSharpDriver** [comment]
I followed your suggestion.  It still fails with the same error messages in the CLI.  I attached the log.
[npm-debug.log](https://github.com/dodekeract/apm/files/1350163/npm-debug.log)

**Comment by FlorianWendelborn** [comment]
@CSharpDriver Can you attach your `package.json`?

**Comment by CSharpDriver** [comment]
Here it is:

 

    On Monday, October 2, 2017 3:50 PM, Florian Wendelborn <notifications@github.com> wrote:
 

 @CSharpDriver Can you attach your package.json?—

**Comment by FlorianWendelborn** [comment]
Doesn't show up on my end. Just open it in your editor and copy-paste it into a code-block, similar to this:

    ```json
    {
      "insert": "your",
      "package": ".json"
    }
    ```

**Comment by CSharpDriver** [comment]
Here's the code for package.json.

```json
{
  "name": "apm",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve -o",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint --type-check",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.0.0",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "rxjs": "^5.4.1",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.2.4",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/language-service": "^4.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
}
```

**Comment by CSharpDriver** [comment]
Hey dodekeract,
I pasted the code as you requested. Perhaps you would be so kind as to review it and make a recommendation for my angular error.
Thanks

**Comment by FlorianWendelborn** [comment]
I have no idea how you ended up in this repository. Where did you get this `package.json` from (especially `"name": "apm"`)? Did you name your own project `apm`?

**Comment by CSharpDriver** [comment]
I downloaded this using a link provided by a Pluralsight video hosted by Debora Kurata

**Comment by FlorianWendelborn** [comment]
I have no idea how that's possible or how it's related to this GitHub project. The only thing these two things have in common is their name in `package.json`. I don't think I can do anything to solve your issue and you should probably try to contact Debora Kurata, post this question to some chatroom with angular users, or post a question on [StackOverflow](https://stackoverflow.com).
